# -*- coding: utf-8 -*-
"""Atividade 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gWAzQ7-W-7uoFszQquXphB_3EMKK1Kba
"""

#1001
A = int(input())
B = int(input())
X = A + B

print(f'X = {X}')

#1003
A = int(input())
B = int(input())
SOMA = A + B
print(f'SOMA = {SOMA}')

#1005
A = float(input())
B = float(input())
MEDIA = ((3.5*A) + (7.5*B))/11
print(f'MEDIA = {MEDIA:.5f}')

#1007
A = int(input())
B = int(input())
C = int(input())
D = int(input())

DIFERENCA = ((A * B) - (C * D))

print(f'DIFERENCA = {DIFERENCA}')

#1009
nome = input()
salario_fixo = float(input())
valor_total_vendido = float(input())
TOTAL = salario_fixo + (valor_total_vendido * 0.15)
print(f'TOTAL = R$ {TOTAL:.2f}')

#1011
R = float(input())
pi = 3.14159
Sphere = (4.0/3) * pi * (R ** 3)
print(f'VOLUME = {Sphere:.3f}')

#1013
a = int(input())
b = int(input())
c = int(input())

maiorAB = (a + b + abs(a - b)) // 2
maior = (maiorAB + c + abs(maiorAB - c)) // 2

print(f'{maior} eh o maior')

#1015
x1, y1 = map(float, input().split())
x2, y2 = map(float, input().split())

distance = (((x2-x1)**2)+((y2-y1)**2)) ** (1/2)

print(f'{distance:.4f}')

#1017
a = int(input())
b = int(input())
car = 12
litros = (a*b) / 12
print(f'{litros:.3f}')

#1019
A = int(input())
hours = A // 3600
A = A % 3600
minutes = A // 60
seconds = A % 60
print(f'{hours}:{minutes}:{seconds}')

#1021
valor = float(input())
valor_em_centavos = int(round(valor * 100))

# Notas
print("NOTAS:")
for nota in [10000, 5000, 2000, 1000, 500, 200]:
    qtd = valor_em_centavos // nota
    print(f"{qtd} nota(s) de R$ {nota / 100:.2f}")
    valor_em_centavos %= nota

# Moedas
print("MOEDAS:")
for moeda in [100, 50, 25, 10, 5, 1]:
    qtd = valor_em_centavos // moeda
    print(f"{qtd} moeda(s) de R$ {moeda / 100:.2f}")
    valor_em_centavos %= moeda